language: node_js

node_js:
- '6.9'

sudo: false

install:
- npm install

script:
- npm run ci

env:
  global:
  - GH_REF: github.com/ScottLogic/StockFlux.git
  - secure: ecJ7bY21fCUBzUnlK11lZWC8lZyXrIxK3jkz6NuI9uEQ0lthmL10s0N+makYA9MJApgm6bgcPQNzJRDZ8ogxMTwMNeD+r4Hj8TcNzI4Mze03KdzGzWv7pY6uW5A2OoonOOLWvIJjK4RZqKTBNbbPt1TWgwS+DY02+QKveUiOsKWKeQ16N1qcH0xPT2cQP98TbioMuBF0hBMekfDmF+RqLPvCzR0Q2QYsh0Yb2uCGdMDQw+VJjlTdNWNaLss+i6DxRjvAm1mecK6OsCsGNJG2fV5DmURSBeP4BD4r+0skLPmYtkiNkJ8bXnDdQwLMbHOwfzxgyE6a2gMdSsR4AQMofjXzFQfwfF/RsC6q7LjvalsytLOJAn1XS7IZ+WRn/PHx7+ceRRCsQYd/dRkWMQgYh6c+cvNSV7yDnnxsbVsrdNP2DIIB+KYLMWD90PH4fH0xlyPvULTjGoJfiKBwjSzNB7Vu8H0M7YtjUD334stI1oTvQwgvN0SA6MWe2BvEBv2avFu5IQ7Kv3mySvlYcFZxHidxTBytKDW809UPs3yHGLCLLvhAnF2BtcvOsqzWKjd5VPUYzGGwEzNeWtiQNyyLNEF5K+/zeeqILEN39YRMQtRjtx8MTzQ9NMz3U3si17htfRHB/R5aO6SWJzABWO+uK3SL2zA6IL5c+9polElssIw=

after_success: bash ./deploy.sh
